# name: fly-deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: superfly/flyctl-actions/setup-flyctl@master
#       - name: Create configs
#         run: echo //npm.pkg.github.com/:_authToken=${{ secrets.GH_REGISTRY_PACKAGES }} > .npmrc && echo @tablerise:registry=https://npm.pkg.github.com/ >> .npmrc
#       - name: Flyio deploy
#         run: flyctl deploy --remote-only
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#       - name: Destroy configs
#         run: rm .npmrc
