name: continuous-delivery-action
on: [pull_request]
jobs:
  backend:
    name: 'Testing Backend'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tablerise'

      - name: Checking Package.json
        run: npm run check-lib

      - name: Install dependencies
        run:  npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}

      - name: Checking lint
        run:  npm run lint

      - name: Checking prettier
        run:  npm run prettier

      - name: Up database container
        run: docker-compose up -d database-test

      - name: Run Tests
        run:  npm run test:coverage

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          threshold_metric: "lines"

      - name: Checking coverage level
        run: npm run check-cov

